//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDLibrary.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DataSources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataSources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CRUDLibrary.Resources.DataSources", typeof(DataSources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to count_emp_by_title.
        /// </summary>
        internal static string count_emp_by_title {
            get {
                return ResourceManager.GetString("count_emp_by_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PKG_PERSON_ADDRESS.
        /// </summary>
        internal static string PKG_PERSON_ADDRESS {
            get {
                return ResourceManager.GetString("PKG_PERSON_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PKG_PERSON_DEPENDENT.
        /// </summary>
        internal static string PKG_PERSON_DEPENDENT {
            get {
                return ResourceManager.GetString("PKG_PERSON_DEPENDENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PKG_PERSON_PROFILE.
        /// </summary>
        internal static string PKG_PERSON_PROFILE {
            get {
                return ResourceManager.GetString("PKG_PERSON_PROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pkg_students2.
        /// </summary>
        internal static string pkg_students2 {
            get {
                return ResourceManager.GetString("pkg_students2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spCopyCurrentAddress.
        /// </summary>
        internal static string spCopyCurrentAddress {
            get {
                return ResourceManager.GetString("spCopyCurrentAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spCreateAddress.
        /// </summary>
        internal static string spCreateAddress {
            get {
                return ResourceManager.GetString("spCreateAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spCreateDependent.
        /// </summary>
        internal static string spCreateDependent {
            get {
                return ResourceManager.GetString("spCreateDependent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spCreatePerson.
        /// </summary>
        internal static string spCreatePerson {
            get {
                return ResourceManager.GetString("spCreatePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spCreateStudent.
        /// </summary>
        internal static string spCreateStudent {
            get {
                return ResourceManager.GetString("spCreateStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spDeleteAddress.
        /// </summary>
        internal static string spDeleteAddress {
            get {
                return ResourceManager.GetString("spDeleteAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spDeleteDependent.
        /// </summary>
        internal static string spDeleteDependent {
            get {
                return ResourceManager.GetString("spDeleteDependent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spDeletePerson.
        /// </summary>
        internal static string spDeletePerson {
            get {
                return ResourceManager.GetString("spDeletePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spDeleteStudent.
        /// </summary>
        internal static string spDeleteStudent {
            get {
                return ResourceManager.GetString("spDeleteStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spGetAddress.
        /// </summary>
        internal static string spGetAddress {
            get {
                return ResourceManager.GetString("spGetAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spGetAddresses.
        /// </summary>
        internal static string spGetAddresses {
            get {
                return ResourceManager.GetString("spGetAddresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spGetDependent.
        /// </summary>
        internal static string spGetDependent {
            get {
                return ResourceManager.GetString("spGetDependent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spGetDependents.
        /// </summary>
        internal static string spGetDependents {
            get {
                return ResourceManager.GetString("spGetDependents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spGetPerson.
        /// </summary>
        internal static string spGetPerson {
            get {
                return ResourceManager.GetString("spGetPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spGetPersonAddresses.
        /// </summary>
        internal static string spGetPersonAddresses {
            get {
                return ResourceManager.GetString("spGetPersonAddresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spGetPersonDependents.
        /// </summary>
        internal static string spGetPersonDependents {
            get {
                return ResourceManager.GetString("spGetPersonDependents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spGetPersons.
        /// </summary>
        internal static string spGetPersons {
            get {
                return ResourceManager.GetString("spGetPersons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spGetStudent.
        /// </summary>
        internal static string spGetStudent {
            get {
                return ResourceManager.GetString("spGetStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spGetStudentById.
        /// </summary>
        internal static string spGetStudentById {
            get {
                return ResourceManager.GetString("spGetStudentById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spGetStudents.
        /// </summary>
        internal static string spGetStudents {
            get {
                return ResourceManager.GetString("spGetStudents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spUpdateAddress.
        /// </summary>
        internal static string spUpdateAddress {
            get {
                return ResourceManager.GetString("spUpdateAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spUpdateDependent.
        /// </summary>
        internal static string spUpdateDependent {
            get {
                return ResourceManager.GetString("spUpdateDependent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spUpdatePerson.
        /// </summary>
        internal static string spUpdatePerson {
            get {
                return ResourceManager.GetString("spUpdatePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spUpdateStudent.
        /// </summary>
        internal static string spUpdateStudent {
            get {
                return ResourceManager.GetString("spUpdateStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Students.
        /// </summary>
        internal static string tblStudents {
            get {
                return ResourceManager.GetString("tblStudents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table1.
        /// </summary>
        internal static string tblTable1 {
            get {
                return ResourceManager.GetString("tblTable1", resourceCulture);
            }
        }
    }
}
